app/models.py
import datetime as dt

from flask_login import UserMixin, AnonymousUserMixin
from sqlalchemy.ext.hybrid import hybrid_property
from werkzeug.security import generate_password_hash, check_password_hash

from app import db


class User(db.Model, UserMixin):

    __tablename__ = 'users'

    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(60), unique=True, nullable=False)
    email = db.Column(db.String(255), unique=True, nullable=False)
    password_hash = db.Column(db.String(255), nullable=False)
    activated = db.Column(db.Boolean, default=False)
    created_at = db.Column(db.DateTime, default=dt.now)

    @hybrid_property
    def password(self):
        return self.password_hash

    @password.setter
    def password(self, password):
        self.password_hash = generate_password_hash(password)

    def check_password(self, password):
        return check_password_hash(self.password, password)

    def __str__(self):
        return '<User %s>' % self.username


class AnonymousUser(AnonymousUserMixin):
    pass

app/user/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, SubmitField
from wtforms.validators import DataRequired, Email, Length, EqualTo


class LoginForm(FlaskForm):
    username = StringField('Username or Email', [DataRequired()])
    password = PasswordField('Password', [DataRequired()])
    login = SubmitField('Login')


class RegisterForm(FlaskForm):
    username = StringField('Username', validators=[DataRequired(), Length(3, 30)])
    email = StringField('Email Address', validators=[DataRequired(), Email(), Length(6, 60)])
    password = PasswordField('Password', validators=[DataRequired(), Length(6, 30)])
    password2 = PasswordField('Confirm password', validators=[DataRequired(),
                              EqualTo('password', message='Password do not match.')])
    register = SubmitField('Register')

app/__init__.py
import os

from flask import Flask, render_template
from flask_login import LoginManager
from flask_bootstrap import Bootstrap
from flask_sqlalchemy import SQLAlchemy
from flask_migrate import Migrate


# instantiate extensions
login_manager = LoginManager()
bootstrap = Bootstrap()
db = SQLAlchemy()
migrate = Migrate()


def create_app():

    from config import config
    from app.user.views import user_blueprint
    from app.main.views import main_blueprint
    from app.models import User, AnonymousUser

    # instantiate app
    app = Flask(__name__)

    # set app config
    env = os.environ.get('FLASK_ENV', 'default')
    app.config.from_object(config[env])
    config[env].configure(app)

    # set up extensions
    for ext in (login_manager, bootstrap, db, migrate):
        ext.init_app(app)

    # register blueprints
    for blueprint in (user_blueprint, main_blueprint):
        app.register_blueprint(blueprint)

    # set up flask login
    @login_manager.user_loader
    def get_user(id):
        return User.query.get(int(id))

    login_manager.login_view = 'user.login'
    login_manager.login_message_category = 'info'
    login_manager.anonymous_user = AnonymousUser

    # error handlers
    @app.errorhandler(401)
    def unauthorized(error):
        return render_template('errors/401.html', error=error), 401

    @app.errorhandler(403)
    def forbidden(error):
        return render_template('errors/403.html', error=error), 403

    @app.errorhandler(404)
    def not_found(error):
        return render_template('errors/404.html', error=error), 404

    @app.errorhandler(500)
    def server_error(error):
        return render_template('errors/500.html', error=error), 500

    return app

app/main/views.py
from flask import render_template, Blueprint


main_blueprint = Blueprint('main', __name__,)


@main_blueprint.route('/')
def home():
    return render_template('main/home.html')


@main_blueprint.route("/about")
def about():
    return render_template("main/about.html")

app/user/views.py
from flask import render_template, Blueprint, url_for, redirect, flash, request
from flask_login import login_user, logout_user, login_required

from app import db
from app.models import User
from app.user.forms import LoginForm, RegisterForm


user_blueprint = Blueprint('user', __name__,)


@user_blueprint.route('/register', methods=['GET', 'POST'])
def register():
    form = RegisterForm(request.form)
    if form.validate_on_submit():
        user = User(
            username=form.username.data, email=form.email.data,
            password=form.password.data)
        db.session.add(user)
        db.session.commit()
        login_user(user)
        flash('Thank you for registering.', 'success')
        return redirect(url_for("main.home"))
    return render_template('user/register.html', form=form)


@user_blueprint.route('/login', methods=['GET', 'POST'])
def login():
    form = LoginForm(request.form)
    if form.validate_on_submit():
        user = User.query.filter(
            db.or_(User.username == form.username.data,
                   User.email == form.username.data)).first()
        if user is not None and user.check_password(form.password.data):
            login_user(user)
            flash('You are logged in. Welcome!', 'success')
            return redirect(url_for('main.home'))
        else:
            flash('Wrong username/email or password.', 'danger')
            return render_template('user/login.html', form=form)
    return render_template('user/login.html', form=form)


@user_blueprint.route('/logout')
@login_required
def logout():
    logout_user()
    flash('You were logged out. Bye!', 'info')
    return redirect(url_for('main.home'))

app/templates/_footer.html
<footer>
    <nav class="navbar fixed-bottom navbar-light bg-light">
        <div class="container">
            <small><span>&copy;<a href="">Enwaweru Eli</a></span></small>
        </div>
    </nav>
</footer>

app/templates/_header.html
<!-- Navigation -->
<nav class="navbar fixed-top navbar-expand-sm navbar-dark bg-dark">
  <div class="container">
    <!-- Navbar Brand -->
    <a class="navbar-brand" href="{{ url_for('main.home') }}">{{ config.APP_NAME }}</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <!-- Main Navigation -->
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link" href="{{ url_for('main.about') }}">About</a>
        </li>
        {% if current_user.is_authenticated %}
        <li class="nav-item">
          <a class="nav-link" href="{{ url_for('user.members') }}">Members</a>
        </li>
        {% endif %}
      </ul>
      <!-- Login/Logout -->
      <ul class="navbar-nav ml-auto">
        <li class="nav-item">
          {% if current_user.is_authenticated %}
          <a class="nav-link" href="{{ url_for('user.logout') }}">Logout</a>
          {% else %}
          <a class="nav-link" href="{{ url_for('user.login') }}">Login</a>
          {% endif %}
        </li>
      </ul>
    </div>
  </div>
</nav>

app/templates/_macros.html
<!-- Put your reusable template code into macros here -->

app/templates/base.html
<!DOCTYPE html>
<html>

  <head>
    <meta charset="utf-8">
    <title>{{ config.APP_NAME }}{% block title %}{% endblock %}</title>
    <!-- meta -->
    <meta name="description" content="">
    <meta name="author" content="">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <!-- styles -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link href="{{url_for('static', filename='main.css')}}" rel="stylesheet" media="screen">
    {% block css %}{% endblock %}
  </head>

  <body>

    {% include '_header.html' %}

    <div class="site-content">
      <div class="container">

        <!-- messages -->
        {% with messages = get_flashed_messages(with_categories=true) %}
        {% if messages %}
        <br>
        <div class="row">
          <div class="col-md-12">
            {% for category, message in messages %}
            <div class="alert alert-{{ category }}">
              <a class="close" title="Close" href="#" data-dismiss="alert">&times;</a>
              {{message}}
            </div>
            {% endfor %}
          </div>
        </div>
        {% endif %}
        {% endwith %}

        <!-- child template -->
        {% block content %}{% endblock %}

        <br>

        <!-- errors -->
        {% if error %}
          <p class="error"><strong>Error:</strong> {{ error }}</p>
        {% endif %}

      </div>
    </div>

    <br><br>

    {% include '_footer.html' %}

    <!-- scripts -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <script src="{{url_for('static', filename='main.js')}}" type="text/javascript"></script>
    {% block js %}{% endblock %}

  </body>
</html>

app/templates/main/about.html
{% extends "base.html" %}

{% block content %}
    <div class="body-content">
        <div>
            <h1>About</h1>
            <hr>
            <p>Add some content here!</p>
        </div>
    </div>
{% endblock %}

app/templates/main/home.html
{% extends "base.html" %}

{% block content %}
    <div>
        <h1>Welcome!</h1>
        <hr>
        <p>Add some content here!</p>
    </div>
{% endblock %}

app/templates/user/login.html
{% extends 'base.html' %}

{% import "bootstrap/wtf.html" as wtf %}

{% block content %}
    <header class="content-header">
        <h1>Login</h1>
    </header>
    <hr>
    <form class="form" role="form" action="{{ url_for('user.login') }}" method="post">
        {{ wtf.quick_form(form) }}
        <p>Need to <a href="{{ url_for('user.register') }}">Register</a>?</p>
    </form>
{% endblock %}

app/templates/user/register.html
{% extends 'base.html' %}

{% import "bootstrap/wtf.html" as wtf %}

{% block content %}
    <header class="content-header">
        <h1>Register</h1>
    </header>
    <hr>
    <form class="form" role="form" action="{{ url_for('user.register') }}" method="post">
        {{ wtf.quick_form(form) }}
        <p>Already have an account? <a href="{{ url_for('user.login') }}">Sign in</a>.</p>
    </form>
{% endblock %}